# aviable platforms: boosty
[record]
platforms = ["boosty"]
file = "video.mp4" # file in content dir from .env
title = "Это просто запись стрима"
description = "Это просто описание записи стрима"
timecodes = """
00:00:00 – Заставка с оригинальной озвучкой
00:13:34 – Начало стрима. Общение
"""
preview = "D:\\preview\\image.jpg"
tags = ["записи стримов"]

# aviable platrforms: tiktok, vk, youtube
[shorts]
platforms = ["tiktok", "vk", "youtube"]
file = "videoclip.mp4" # file in content dir from .env
title = "Самый невезучий персонаж в игре"
tags = ["#kingdomcomedeliverance"]
default_tags = ["#смешныемоменты"]
description = """
Привет! Спасибо за просмотр!
"""
yt_playlist = "PLTZz9Mfa8xs-Qwefewfem4lrL0RYPtn" # null if no playlist
